CREATE DATABASE cmDB;

USE cmdb;
CREATE TABLE announcement(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  description NVARCHAR(255) NOT NULL ,
  title NVARCHAR(255) NOT NULL
) ENGINE = InnoDB;


CREATE TABLE course(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY ,
  name VARCHAR(255) NOT NULL ,
  duration INT NOT NULL ,
  description TEXT(255) NOT NULL ,
  price DOUBLE NOT NULL
) ENGINE = InnoDB;


CREATE TABLE user(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY ,
  title VARCHAR(255) NOT NULL ,
  first_name VARCHAR(255) NOT NULL ,
  last_name VARCHAR(255) NOT NULL ,
  age INT NOT NULL ,
  email VARCHAR(255) NOT NULL UNIQUE ,
  description TEXT DEFAULT NULL ,
  phone_number VARCHAR(255) NOT NULL ,
  role INT NOT NULL ,
  login VARCHAR(255) NOT NULL UNIQUE ,
  password VARCHAR(255) NOT NULL
)ENGINE = InnoDB;


CREATE TABLE score(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY ,
  attendance INT NOT NULL ,
  knowledge INT NOT NULL
)ENGINE = InnoDB;
